name: Rust

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo run
