name: Rust

on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo run
